services:
  db:
    image: postgres:17-alpine
    container_name: challenge-db
    environment:
      POSTGRES_USER: challenge-user
      POSTGRES_PASSWORD: challenge-pass
      POSTGRES_DB: challenge-db
    volumes:
      - challenge-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: challenge-api
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  challenge-db-data:
